<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="toolRoom.aspx.cs" Inherits="midsim.toolRoom" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            text-align: center;
            font-size: 32pt;
            color: #6375B3;
        }
        .button{
            font-size: 20px;
            font-family: 'Gen Jyuu Gothic Medium';
            background-color: white;
            border-color: #FFD7BD;
            border-style: Double;
            border-width: 5px;
            color: #AE4427;
        }
        .auto-style2 {
            width: 100%;
        }
        .auto-style3 {
            font-size: x-large;
        }
        .auto-style4 {
            font-size: large;
            position: relative;
            left: 3px;
            top: 0px;
        }
        .auto-style5 {
            width: 839px;
        }
        .auto-style6 {
            width: 300px;
        }
        .auto-style7 {
            font-size: large;
        }
    </style>
</head>
<body style="background-position: center center; background-size: cover; font-family: 'Gen Jyuu Gothic Medium'; background-image: url('卡納赫拉桌布手工餅乾.jpg'); background-repeat: no-repeat; background-attachment: fixed; height: 307px;">
    <form id="form1" runat="server">
        <div class="auto-style1" style="position: relative">
            歡迎來到工具間<table class="auto-style2" style="position: relative">
                <tr>
                    <td class="auto-style6">&nbsp;</td>
                    <td class="auto-style5">
                        <asp:Label ID="toolNameLB" runat="server" CssClass="auto-style3" style="position: relative" Text="工具名"></asp:Label>
                        <asp:TextBox ID="inquireToolTB" runat="server" CssClass="auto-style4" Height="24px" Width="163px"></asp:TextBox>
                    </td>
                    <td>
                        <asp:SqlDataSource ID="inquireToolDetail" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT toolName FROM toolData WHERE (toolName = @toolName)">
                            <SelectParameters>
                                <asp:ControlParameter ControlID="inquireToolTB" Name="toolName" PropertyName="Text" />
                            </SelectParameters>
                        </asp:SqlDataSource>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style6">&nbsp;</td>
                    <td class="auto-style5">
                        <asp:Button ID="inquireBT" runat="server" Text="查詢工具" CssClass="button" Font-Names="源泉圓體 M" Height="45px" OnClick="inquireBT_Click"/>
                    </td>
                    <td>
                        <asp:DetailsView ID="inquireToolDetailsView" runat="server" AutoGenerateRows="False" BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" CellPadding="2" CssClass="auto-style7" DataSourceID="inquireToolDetail" ForeColor="Black" GridLines="None" Height="50px" Width="210px" OnPageIndexChanging="inquireToolDetailsView_PageIndexChanging" Visible="False">
                            <AlternatingRowStyle BackColor="PaleGoldenrod" />
                            <EditRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
                            <Fields>
                                <asp:BoundField DataField="toolName" HeaderText="toolName" SortExpression="toolName" />
                            </Fields>
                            <FooterStyle BackColor="Tan" />
                            <HeaderStyle BackColor="Tan" Font-Bold="True" />
                            <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
                        </asp:DetailsView>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style6">&nbsp;</td>
                    <td class="auto-style5">
                        <asp:GridView ID="toolGridView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" CssClass="auto-style7" DataKeyNames="Id" DataSourceID="toolSqlDataSource" ForeColor="#333333" GridLines="None" Width="832px" OnSelectedIndexChanged="toolGridView_SelectedIndexChanged">
                            <AlternatingRowStyle BackColor="White" />
                            <Columns>
                                <asp:BoundField DataField="Id" HeaderText="工具號" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                                <asp:BoundField DataField="toolName" HeaderText="工具名" SortExpression="toolName" />
                                <asp:BoundField DataField="ownerName" HeaderText="擁有人姓名" SortExpression="ownerName" />
                                <asp:BoundField DataField="userName" HeaderText="使用人姓名" SortExpression="userName" />
                                <asp:BoundField DataField="userPhone" HeaderText="使用人電話" SortExpression="userPhone" />
                                <asp:BoundField DataField="startDate" HeaderText="開始使用日期" SortExpression="startDate" />
                            </Columns>
                            <EditRowStyle BackColor="#2461BF" />
                            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                            <RowStyle BackColor="#EFF3FB" />
                            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                            <SortedAscendingCellStyle BackColor="#F5F7FB" />
                            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                            <SortedDescendingCellStyle BackColor="#E9EBEF" />
                            <SortedDescendingHeaderStyle BackColor="#4870BE" />
                        </asp:GridView>
                    </td>
                    <td>
                        <asp:SqlDataSource ID="toolSqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM toolData WHERE (Id = @id) AND (ownerName = @userName1) AND (userName = @userName2)" SelectCommand="SELECT toolData.Id, toolData.toolName, toolData.ownerName, toolData.userName, userData.userPhone, toolData.startDate FROM toolData INNER JOIN userData ON toolData.userName = userData.userName WHERE (toolData.toolName = @toolName)" UpdateCommand="UPDATE toolData SET userName = @userName3, startDate = GETDATE() FROM toolData INNER JOIN userData ON toolData.userName = userData.userName WHERE (toolData.Id = @id)">
                            <DeleteParameters>
                                <asp:ControlParameter ControlID="toolGridView" Name="id" PropertyName="SelectedDataKey" />
                                <asp:SessionParameter Name="userName1" SessionField="userName" />
                                <asp:SessionParameter Name="userName2" SessionField="userName" />
                            </DeleteParameters>
                            <SelectParameters>
                                <asp:SessionParameter Name="toolName" SessionField="toolName" />
                            </SelectParameters>
                            <UpdateParameters>
                                <asp:SessionParameter Name="userName3" SessionField="userName" />
                                <asp:ControlParameter ControlID="toolGridView" Name="id" PropertyName="SelectedDataKey" />
                            </UpdateParameters>
                        </asp:SqlDataSource>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style6">&nbsp;</td>
                    <td class="auto-style5">&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            </table>
        </div>
    </form>
</body>
</html>
